language: python




deploy:
  - provider: codedeploy
    revision_type: github
    wait_until_deployed: true
    access_key_id: $AWS_ACC_KEY
    secret_access_key: $AWS_SECRET
    application: $CODE_DEPLOY_APP
    deployment_group: $DEPLOY_GROUP
    region: $REGION