version: '3.7'
services:
  nginx:
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached
  backend:
    volumes:
      - ./backend:/app/:cached
    depends_on:
      - "postgres"
#  frontend:
#    environment:
#      NODE_ENV: 'production'
#    volumes:
#      - './frontend:/app:cached'
#      - './frontend/node_modules:/app/node_modules:cached'

volumes:
  db-data: