version: '3.7'

services:
  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
  frontend:
    environment:
      - NODE_ENV=production
  worker:
    command: celery worker -A app.tasks --loglevel=DEBUG -Q main-queue -c 1 -b ${REDIS_DB_URL}
    volumes:
      - ./backend:/app/:cached

  backend:
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached