version: '3.7'
services:
  nginx:
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached
  worker:
    command: celery worker -A app.tasks --loglevel=DEBUG -Q main-queue -c 1 -b ${REDIS_DB_URL}
    volumes:
      - ./backend:/app/:cached
  flower:
    image: mher/flower
    command: flower --broker=${REDIS_DB_URL} --port=5555
    ports:
      - 5555:5555
    depends_on:
      - "redis"
  backend:
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    depends_on:
      - "postgres"
      - "redis"

  frontend:
    environment:
      - NODE_ENV=production
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'

volumes:
  db-data: