version: '3.7'
services:
  nginx:
    image: nginx:1.17
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend

  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: .
      S3_KEY_INTERNAL: '${S3_KEY_INTERNAL}'
      S3_SECRET_INTERNAL: '${S3_SECRET_INTERNAL}'
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_URL_PORT}/${POSTGRES_DB_NAME}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      REDIS_DB_URL: '${REDIS_DB_URL}'
      POSTGRES_DB_NAME: '${POSTGRES_DB_NAME}'
      POSTGRES_URL_PORT: '${POSTGRES_URL_PORT}'

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_URL_PORT}/${POSTGRES_DB_NAME}'
      HASH_KEY: "${HASH_KEY}"
      HASH_ALG: "${HASH_ALG}"
      JWT_Token_TTL: 120
      S3_BUCKET_NAME: '${S3_BUCKET_NAME}'
      S3_KEY_INTERNAL: '${S3_KEY_INTERNAL}'
      S3_SECRET_INTERNAL: '${S3_SECRET_INTERNAL}'
      REDIS_DB_URL: '${REDIS_DB_URL}'
      POSTGRES_DB_NAME: '${POSTGRES_DB_NAME}'
      POSTGRES_URL_PORT: '${POSTGRES_URL_PORT}'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8888/api"]
      interval: 15s
      timeout: 30s
      retries: 5

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true


